### ISSUE TITLE
Import error on M1

### ISSUE THREAD

**Issue by carterlasalle** [scorpion81/Blender-Molecular-Script#17]
<img width="1502" alt="Screenshot 2022-09-01 at 2 19 53 PM" src="https://user-images.githubusercontent.com/50027436/188015107-1bcdc3e0-bba4-4d78-952e-386c2df64df7.png">
<img width="1450" alt="Screenshot 2022-09-01 at 2 20 15 PM" src="https://user-images.githubusercontent.com/50027436/188015180-e3356e69-8094-4987-967b-04d4884939ea.png">

I am on a m1 mac, and I have a problem when importing because it is requiring an architecture that I don't have. @scorpion81 

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/__init__.py", line 42, in register
    from . import properties, ui, operators
  File "/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/operators.py", line 7, in <module>
    from . import simulate, core
ImportError: dlopen(/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/core.cpython-310-darwin.so, 0x0002): tried: '/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/core.cpython-310-darwin.so' (fat file, but missing compatible architecture (have 'x86_64,arm64e', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/core.cpython-310-darwin.so' (no such file), '/Users/Rocket1/Library/Application Support/Blender/3.4/scripts/addons/molecular/core.cpython-310-darwin.so' (fat file, but missing compatible architecture (have 'x86_64,arm64e', need 'arm64'))
```

**Comment by scorpion81** [comment]
Hi, could you please test the latest release ? I included arm64 into the mac os fat binary there as well now.

**Comment by carterlasalle** [comment]
> Hi, could you please test the latest release ? I included arm64 into the mac os fat binary there as well now.

Hey! I got it to work! Is there some type of tutorial?

**Comment by ellumpine** [comment]
hey, I use Blender 4.3.2 (the last version now 5.01.2025) unfortunately this amazing add on does'nt work. is there any workaround?
